# Generated by Django 6.0.4 on 2026-05-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_partner_logo'),
        ('website', '0011_blogindexpage_customdocument_customimage_blogpage_and_more'),
    ]

    operations = [
    ]
